apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
    env: test
  name: admin
  namespace: test
spec:
  selector:
    app: admin
    env: test
  ports:
  - name: http
    port: 8182
    targetPort: 8182