apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: admin
    env: test
  name:  admin
  namespace: test
spec:
  tls:
  - hosts:
    -  admin
  rules:
  - host: admin.com
    http:
      paths:
      - backend:
          serviceName: admin
          servicePort: 8182
        path: /
status:
  loadBalancer:
    ingress:
    - {}