apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: admin
    env: test
  name: admin
  namespace: test
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin
        env: test
    spec:
      containers:
      - name: admin
        image: admin:latest
        imagePullPolicy: Always            
        ports:
        - containerPort: 8182
          name: http  